In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import json
#import pickle
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv(r"C:\Users\darmo\Desktop\ESCP\Machine Learning\Project\train\train.csv")

In [3]:
len(df)

7265055

In [23]:
df['keywords'][0].split()

['fibre:16;quoi:1;dangers:1;combien:1;hightech:16;que:16;est:1;recevra:1;operateur:1;quelles:1;installation:1;monde:1;tout:1;oblige:1;differences:1;existe:1;adsl:1;choisir:1;concerne:1;sante:1;telephonique:1;com:1;chez:1;faire:1;quelle:1;debit:1;les:2;cable:1;quels:2;fttb:1;box:1;ligne:1;pour:3;sur:16;pose:16;devient:1;meilleur:1;fttla:1;suis:3;des:1;linternaute:1;coute:1;avec:1;ftth:1;avoir:1;qui:2;avant:1;effectue:1;libre:1;debits:1;celui:1;delais:1;internet:16;abonner:1;questions:16;toujours:1;sont:2;mon:1']

In [24]:
df['keywords'][0]

'fibre:16;quoi:1;dangers:1;combien:1;hightech:16;que:16;est:1;recevra:1;operateur:1;quelles:1;installation:1;monde:1;tout:1;oblige:1;differences:1;existe:1;adsl:1;choisir:1;concerne:1;sante:1;telephonique:1;com:1;chez:1;faire:1;quelle:1;debit:1;les:2;cable:1;quels:2;fttb:1;box:1;ligne:1;pour:3;sur:16;pose:16;devient:1;meilleur:1;fttla:1;suis:3;des:1;linternaute:1;coute:1;avec:1;ftth:1;avoir:1;qui:2;avant:1;effectue:1;libre:1;debits:1;celui:1;delais:1;internet:16;abonner:1;questions:16;toujours:1;sont:2;mon:1'

In [3]:
df.head(15)

    ID                                           keywords  age sex
0    1  fibre:16;quoi:1;dangers:1;combien:1;hightech:1...   62   F
1    2                     restaurant:1;marrakech.shtml:1   35   M
2    3  payer:1;faq:1;taxe:1;habitation:1;macron:1;qui...   45   F
3    4  rigaud:3;laurent:3;photo:11;profile:8;photopro...   46   F
4    5  societe:1;disparition:1;proche:1;m%c3%a9lanie....   42   F
5    6  portes:1;prives:1;entre:1;conso:1;mer:1;enfant...   49   F
6    8  son:1;laposte:1;forum:1;mobile:1;affich:1;forf...   47   F
7    9  location:1;preavis:1;mois:1;faq:1;modele:1;dep...   52   M
8   12  iphone:1;homme:1;vue:1;deuxieme:1;internet:1;g...   49   F
9   13                                                NaN   46   M
10  14                                                NaN   44   M
11  15  p1_1697208:1;metre:1;jcms:1;prix:1;immmobilier...   65   F
12  16  censure:1;vox:1;cible:1;societe:1;antiraciste:...   34   F
13  18  refuser:1;deuxieme:1;maelys:1;forum:1;censure:...   34   F
14  20                                                NaN   37   F

In [54]:
df_without_na = df.dropna(subset = ['keywords'])

In [55]:
df_without_na.head(20)

    ID                                           keywords  age sex
0    1  fibre:16;quoi:1;dangers:1;combien:1;hightech:1...   62   F
1    2                     restaurant:1;marrakech.shtml:1   35   M
2    3  payer:1;faq:1;taxe:1;habitation:1;macron:1;qui...   45   F
3    4  rigaud:3;laurent:3;photo:11;profile:8;photopro...   46   F
4    5  societe:1;disparition:1;proche:1;m%c3%a9lanie....   42   F
5    6  portes:1;prives:1;entre:1;conso:1;mer:1;enfant...   49   F
6    8  son:1;laposte:1;forum:1;mobile:1;affich:1;forf...   47   F
7    9  location:1;preavis:1;mois:1;faq:1;modele:1;dep...   52   M
8   12  iphone:1;homme:1;vue:1;deuxieme:1;internet:1;g...   49   F
11  15  p1_1697208:1;metre:1;jcms:1;prix:1;immmobilier...   65   F
12  16  censure:1;vox:1;cible:1;societe:1;antiraciste:...   34   F
13  18  refuser:1;deuxieme:1;maelys:1;forum:1;censure:...   34   F
15  21  amies:1;statines:1;homme:1;des:1;garde:1;vue:1...   43   M
17  23  leila:1;nouvelle:1;boudjahlat:1;censure:1;soci...   47   M
18  24  tabac:1;les:1;terrorisme:1;excuses:2;luxe:2;do...   40   M
19  27  definition:1;sgpt:1;asat:1;sgot:1;faq:2;transa...   35   F
20  28  lively:1;messi:1;enzo:1;nolwenn:1;diaz:1;kourt...   50   F
21  30  deuxieme:1;look:1;films:1;flash:1;vue:1;place:...   39   M
23  33  adams:1;refaeli:1;paltrow:1;brodier:2;ariane:2...   52   F
25  39  psychologue+clinicienne:1;search:1;rwpl:1;tours:1   28   F

In [5]:
df_without_na.head(20)

    ID                                           keywords  age sex
0    1  fibre:16;quoi:1;dangers:1;combien:1;hightech:1...   62   F
1    2                     restaurant:1;marrakech.shtml:1   35   M
2    3  payer:1;faq:1;taxe:1;habitation:1;macron:1;qui...   45   F
3    4  rigaud:3;laurent:3;photo:11;profile:8;photopro...   46   F
4    5  societe:1;disparition:1;proche:1;m%c3%a9lanie....   42   F
5    6  portes:1;prives:1;entre:1;conso:1;mer:1;enfant...   49   F
6    8  son:1;laposte:1;forum:1;mobile:1;affich:1;forf...   47   F
7    9  location:1;preavis:1;mois:1;faq:1;modele:1;dep...   52   M
8   12  iphone:1;homme:1;vue:1;deuxieme:1;internet:1;g...   49   F
9   15  p1_1697208:1;metre:1;jcms:1;prix:1;immmobilier...   65   F
10  16  censure:1;vox:1;cible:1;societe:1;antiraciste:...   34   F
11  18  refuser:1;deuxieme:1;maelys:1;forum:1;censure:...   34   F
12  21  amies:1;statines:1;homme:1;des:1;garde:1;vue:1...   43   M
13  23  leila:1;nouvelle:1;boudjahlat:1;censure:1;soci...   47   M
14  24  tabac:1;les:1;terrorisme:1;excuses:2;luxe:2;do...   40   M
15  27  definition:1;sgpt:1;asat:1;sgot:1;faq:2;transa...   35   F
16  28  lively:1;messi:1;enzo:1;nolwenn:1;diaz:1;kourt...   50   F
17  30  deuxieme:1;look:1;films:1;flash:1;vue:1;place:...   39   M
18  33  adams:1;refaeli:1;paltrow:1;brodier:2;ariane:2...   52   F
19  39  psychologue+clinicienne:1;search:1;rwpl:1;tours:1   28   F

In [6]:
testsplit = df['keywords'][0]

In [7]:
testsplit

'fibre:16;quoi:1;dangers:1;combien:1;hightech:16;que:16;est:1;recevra:1;operateur:1;quelles:1;installation:1;monde:1;tout:1;oblige:1;differences:1;existe:1;adsl:1;choisir:1;concerne:1;sante:1;telephonique:1;com:1;chez:1;faire:1;quelle:1;debit:1;les:2;cable:1;quels:2;fttb:1;box:1;ligne:1;pour:3;sur:16;pose:16;devient:1;meilleur:1;fttla:1;suis:3;des:1;linternaute:1;coute:1;avec:1;ftth:1;avoir:1;qui:2;avant:1;effectue:1;libre:1;debits:1;celui:1;delais:1;internet:16;abonner:1;questions:16;toujours:1;sont:2;mon:1'

In [8]:
listkeywords = testsplit.split(";")

In [9]:
print(listkeywords)

['fibre:16', 'quoi:1', 'dangers:1', 'combien:1', 'hightech:16', 'que:16', 'est:1', 'recevra:1', 'operateur:1', 'quelles:1', 'installation:1', 'monde:1', 'tout:1', 'oblige:1', 'differences:1', 'existe:1', 'adsl:1', 'choisir:1', 'concerne:1', 'sante:1', 'telephonique:1', 'com:1', 'chez:1', 'faire:1', 'quelle:1', 'debit:1', 'les:2', 'cable:1', 'quels:2', 'fttb:1', 'box:1', 'ligne:1', 'pour:3', 'sur:16', 'pose:16', 'devient:1', 'meilleur:1', 'fttla:1', 'suis:3', 'des:1', 'linternaute:1', 'coute:1', 'avec:1', 'ftth:1', 'avoir:1', 'qui:2', 'avant:1', 'effectue:1', 'libre:1', 'debits:1', 'celui:1', 'delais:1', 'internet:16', 'abonner:1', 'questions:16', 'toujours:1', 'sont:2', 'mon:1']

In [10]:
type(listkeywords)

list

In [11]:
newlist = []
for n in listkeywords:
        newlist += n.split(':')

In [12]:
print(newlist)

['fibre', '16', 'quoi', '1', 'dangers', '1', 'combien', '1', 'hightech', '16', 'que', '16', 'est', '1', 'recevra', '1', 'operateur', '1', 'quelles', '1', 'installation', '1', 'monde', '1', 'tout', '1', 'oblige', '1', 'differences', '1', 'existe', '1', 'adsl', '1', 'choisir', '1', 'concerne', '1', 'sante', '1', 'telephonique', '1', 'com', '1', 'chez', '1', 'faire', '1', 'quelle', '1', 'debit', '1', 'les', '2', 'cable', '1', 'quels', '2', 'fttb', '1', 'box', '1', 'ligne', '1', 'pour', '3', 'sur', '16', 'pose', '16', 'devient', '1', 'meilleur', '1', 'fttla', '1', 'suis', '3', 'des', '1', 'linternaute', '1', 'coute', '1', 'avec', '1', 'ftth', '1', 'avoir', '1', 'qui', '2', 'avant', '1', 'effectue', '1', 'libre', '1', 'debits', '1', 'celui', '1', 'delais', '1', 'internet', '16', 'abonner', '1', 'questions', '16', 'toujours', '1', 'sont', '2', 'mon', '1']

In [ ]:
type(newlist)

In [16]:
#fonction pour separer les mots clés dans un dataset afin de pouvoir les manipuler 
def splitwords_to_df(linekeyword):
    words = []
    frequencies = []
    newlist = []
    listkeywords = linekeyword.split(";")
    for n in listkeywords:
        newlist = newlist + n.split(':')
    for n in newlist:
        if newlist.index(n)%2 == 0:
            words.append(n)
        else:
            # on force le passage en int sinon les frequences sont en string 
            frequencies.append(int(n))
    finaldf = pd.DataFrame({"keywords": words, "frequency": frequencies}) 
    # finaltuple = tuple(map(lambda x, y: (x,y) , words, frequencies)) test avec un tupple en output
    return finaldf

In [17]:
row1 = splitwords_to_df(df['keywords'][0])
row2 = splitwords_to_df(df['keywords'][1])

In [18]:
row1

        keywords  frequency
0          fibre         16
1           quoi          1
2        dangers          1
3        combien          1
4       hightech         16
5            que         16
6            est          1
7        recevra          1
8      operateur          1
9        quelles          1
10  installation          1
11         monde          1
12          tout          1
13        oblige          1
14   differences          1
15        existe          1
16          adsl          1
17       choisir          1
18      concerne          1
19         sante          1
20  telephonique          1
21           com          1
22          chez          1
23         faire          1
24        quelle          1
25         debit          1
26           les          2
27         cable          1
28         quels          2
29          fttb          1
30           box          1
31         ligne          1
32          pour          3
33           sur         16
34          pose         16
35       devient          1
36      meilleur          1
37         fttla          1
38          suis          3
39           des          1
40   linternaute          1
41         coute          1
42          avec          1
43          ftth          1
44         avoir          1
45           qui          2
46         avant          1
47      effectue          1
48         libre          1
49        debits          1
50         celui          1
51        delais          1
52      internet         16
53       abonner          1
54     questions         16
55      toujours          1
56          sont          2
57           mon          1

In [19]:
type(row1)

pandas.core.frame.DataFrame

In [20]:
row2

          keywords  frequency
0       restaurant          1
1  marrakech.shtml          1

In [21]:
finaldf = row1.merge(row2, on ='keywords',how = 'outer')

In [22]:
finaldf

           keywords  frequency_x  frequency_y
0             fibre         16.0          NaN
1              quoi          1.0          NaN
2           dangers          1.0          NaN
3           combien          1.0          NaN
4          hightech         16.0          NaN
5               que         16.0          NaN
6               est          1.0          NaN
7           recevra          1.0          NaN
8         operateur          1.0          NaN
9           quelles          1.0          NaN
10     installation          1.0          NaN
11            monde          1.0          NaN
12             tout          1.0          NaN
13           oblige          1.0          NaN
14      differences          1.0          NaN
15           existe          1.0          NaN
16             adsl          1.0          NaN
17          choisir          1.0          NaN
18         concerne          1.0          NaN
19            sante          1.0          NaN
20     telephonique          1.0          NaN
21              com          1.0          NaN
22             chez          1.0          NaN
23            faire          1.0          NaN
24           quelle          1.0          NaN
25            debit          1.0          NaN
26              les          2.0          NaN
27            cable          1.0          NaN
28            quels          2.0          NaN
29             fttb          1.0          NaN
30              box          1.0          NaN
31            ligne          1.0          NaN
32             pour          3.0          NaN
33              sur         16.0          NaN
34             pose         16.0          NaN
35          devient          1.0          NaN
36         meilleur          1.0          NaN
37            fttla          1.0          NaN
38             suis          3.0          NaN
39              des          1.0          NaN
40      linternaute          1.0          NaN
41            coute          1.0          NaN
42             avec          1.0          NaN
43             ftth          1.0          NaN
44            avoir          1.0          NaN
45              qui          2.0          NaN
46            avant          1.0          NaN
47         effectue          1.0          NaN
48            libre          1.0          NaN
49           debits          1.0          NaN
50            celui          1.0          NaN
51           delais          1.0          NaN
52         internet         16.0          NaN
53          abonner          1.0          NaN
54        questions         16.0          NaN
55         toujours          1.0          NaN
56             sont          2.0          NaN
57              mon          1.0          NaN
58       restaurant          NaN          1.0
59  marrakech.shtml          NaN          1.0

In [23]:
finaldf = finaldf.fillna(0)

In [24]:
finaldf["frequency_x"]

0     16.0
1      1.0
2      1.0
3      1.0
4     16.0
5     16.0
6      1.0
7      1.0
8      1.0
9      1.0
10     1.0
11     1.0
12     1.0
13     1.0
14     1.0
15     1.0
16     1.0
17     1.0
18     1.0
19     1.0
20     1.0
21     1.0
22     1.0
23     1.0
24     1.0
25     1.0
26     2.0
27     1.0
28     2.0
29     1.0
30     1.0
31     1.0
32     3.0
33    16.0
34    16.0
35     1.0
36     1.0
37     1.0
38     3.0
39     1.0
40     1.0
41     1.0
42     1.0
43     1.0
44     1.0
45     2.0
46     1.0
47     1.0
48     1.0
49     1.0
50     1.0
51     1.0
52    16.0
53     1.0
54    16.0
55     1.0
56     2.0
57     1.0
58     0.0
59     0.0
Name: frequency_x, dtype: float64

In [25]:
finaldf['frequency'] = finaldf.apply(lambda row : row['frequency_x'] + row['frequency_y'], axis = 1 )
finaldf = finaldf.drop({"frequency_x","frequency_y"}, axis = 1)

In [26]:
finaldf

           keywords  frequency
0             fibre       16.0
1              quoi        1.0
2           dangers        1.0
3           combien        1.0
4          hightech       16.0
5               que       16.0
6               est        1.0
7           recevra        1.0
8         operateur        1.0
9           quelles        1.0
10     installation        1.0
11            monde        1.0
12             tout        1.0
13           oblige        1.0
14      differences        1.0
15           existe        1.0
16             adsl        1.0
17          choisir        1.0
18         concerne        1.0
19            sante        1.0
20     telephonique        1.0
21              com        1.0
22             chez        1.0
23            faire        1.0
24           quelle        1.0
25            debit        1.0
26              les        2.0
27            cable        1.0
28            quels        2.0
29             fttb        1.0
30              box        1.0
31            ligne        1.0
32             pour        3.0
33              sur       16.0
34             pose       16.0
35          devient        1.0
36         meilleur        1.0
37            fttla        1.0
38             suis        3.0
39              des        1.0
40      linternaute        1.0
41            coute        1.0
42             avec        1.0
43             ftth        1.0
44            avoir        1.0
45              qui        2.0
46            avant        1.0
47         effectue        1.0
48            libre        1.0
49           debits        1.0
50            celui        1.0
51           delais        1.0
52         internet       16.0
53          abonner        1.0
54        questions       16.0
55         toujours        1.0
56             sont        2.0
57              mon        1.0
58       restaurant        1.0
59  marrakech.shtml        1.0

In [27]:
# Creation d'une fonction pour merger 2 dataframe
def merge_df_on_keywords(df1,df2):
    finaldf = df1.merge(df2, on ='keywords',how = 'outer')
    finaldf = finaldf.fillna(0)
    finaldf['frequency'] = finaldf.apply(lambda row : row['frequency_x'] + row['frequency_y'], axis = 1 )
    finaldf = finaldf.drop({"frequency_x","frequency_y"}, axis = 1)
    return finaldf

In [28]:
testdf = merge_df_on_keywords(row1,row2)

In [29]:
testdf

           keywords  frequency
0             fibre       16.0
1              quoi        1.0
2           dangers        1.0
3           combien        1.0
4          hightech       16.0
5               que       16.0
6               est        1.0
7           recevra        1.0
8         operateur        1.0
9           quelles        1.0
10     installation        1.0
11            monde        1.0
12             tout        1.0
13           oblige        1.0
14      differences        1.0
15           existe        1.0
16             adsl        1.0
17          choisir        1.0
18         concerne        1.0
19            sante        1.0
20     telephonique        1.0
21              com        1.0
22             chez        1.0
23            faire        1.0
24           quelle        1.0
25            debit        1.0
26              les        2.0
27            cable        1.0
28            quels        2.0
29             fttb        1.0
30              box        1.0
31            ligne        1.0
32             pour        3.0
33              sur       16.0
34             pose       16.0
35          devient        1.0
36         meilleur        1.0
37            fttla        1.0
38             suis        3.0
39              des        1.0
40      linternaute        1.0
41            coute        1.0
42             avec        1.0
43             ftth        1.0
44            avoir        1.0
45              qui        2.0
46            avant        1.0
47         effectue        1.0
48            libre        1.0
49           debits        1.0
50            celui        1.0
51           delais        1.0
52         internet       16.0
53          abonner        1.0
54        questions       16.0
55         toujours        1.0
56             sont        2.0
57              mon        1.0
58       restaurant        1.0
59  marrakech.shtml        1.0

In [30]:
type(testdf)

pandas.core.frame.DataFrame

In [31]:
# le dataset doit avoir seulement une colonne keywords et frequency sinon il y aura un problème au niveau des objets
# A ajouter : regrouper les mots ensembles  group by et addition des frequency ?? 
def keyword_list_frequency(df,nb_line):
    endDf = pd.DataFrame(columns = ['keywords','frequency']) 
    for i in range(0,nb_line):
        if i%2 == 0:
            vocablist1 = splitwords_to_df(df['keywords'][i])
            vocablist2 = splitwords_to_df(df['keywords'][i+1])
            # buggera si la row i+1 n'existe pas à modifier plus tard 
            temporarydf =  merge_df_on_keywords(vocablist1,vocablist2)
        endDf = merge_df_on_keywords(endDf,temporarydf)
        # A ajouter : regrouper les mots ensembles  group by et addition des frequency ??  ne se fait pas à ce niveau là 
    return endDf

In [55]:
test_lines = keyword_list_frequency(df_without_na,100)

In [47]:
test_lines

            keywords  frequency
0              fibre       32.0
1               quoi        2.0
2            dangers        2.0
3            combien        2.0
4           hightech       32.0
5                que       32.0
6                est        2.0
7            recevra        2.0
8          operateur        2.0
9            quelles        2.0
10      installation        2.0
11             monde        2.0
12              tout        2.0
13            oblige        2.0
14       differences        2.0
15            existe        2.0
16              adsl        2.0
17           choisir        2.0
18          concerne        2.0
19             sante        2.0
20      telephonique        2.0
21               com        2.0
22              chez        2.0
23             faire        2.0
24            quelle        2.0
25             debit        2.0
26               les        6.0
27             cable        2.0
28             quels        4.0
29              fttb        2.0
..               ...        ...
140         portable        2.0
141             8e5f        2.0
142           banque        2.0
143             actu        2.0
144              son        2.0
145          laposte        2.0
146           mobile        4.0
147          forfait        2.0
148        consulter        2.0
149         location        2.0
150          preavis        2.0
151             mois        2.0
152           modele        2.0
153           depart        2.0
154           iphone        2.0
155              ios        2.0
156          paysage        2.0
157             mode        2.0
158        ebusiness        2.0
159  fonctionnalites        2.0
160           france        2.0
161       p1_1697208        2.0
162            metre        2.0
163             jcms        2.0
164             prix        2.0
165      immmobilier        2.0
166           record        2.0
167              bat        2.0
168            paris        2.0
169            carre        2.0

[170 rows x 2 columns]

In [185]:
t = test_100_lines.groupby(['keywords'])

In [187]:
print(t)

<pandas.core.groupby.groupby.DataFrameGroupBy object at 0x000001768A6BF4A8>

Zone de test

In [109]:
row1 = splitwords_to_df(df['keywords'][0])
row2 = splitwords_to_df(df['keywords'][1])
row3 = splitwords_to_df(df['keywords'][2])
row4 = splitwords_to_df(df['keywords'][3])

In [111]:
df1 = merge_df_on_keywords(row1,row2)

In [113]:
df2 = merge_df_on_keywords(row3,row4)

In [128]:
final = merge_df_on_keywords(df1,df2)

In [188]:
df["keywords"][9]

nan

In [189]:
df.head(10)

   ID                                           keywords  age sex
0   1  fibre:16;quoi:1;dangers:1;combien:1;hightech:1...   62   F
1   2                     restaurant:1;marrakech.shtml:1   35   M
2   3  payer:1;faq:1;taxe:1;habitation:1;macron:1;qui...   45   F
3   4  rigaud:3;laurent:3;photo:11;profile:8;photopro...   46   F
4   5  societe:1;disparition:1;proche:1;m%c3%a9lanie....   42   F
5   6  portes:1;prives:1;entre:1;conso:1;mer:1;enfant...   49   F
6   8  son:1;laposte:1;forum:1;mobile:1;affich:1;forf...   47   F
7   9  location:1;preavis:1;mois:1;faq:1;modele:1;dep...   52   M
8  12  iphone:1;homme:1;vue:1;deuxieme:1;internet:1;g...   49   F
9  13                                                NaN   46   M

In [192]:
d10 = df[:10]

In [193]:
d10

   ID                                           keywords  age sex
0   1  fibre:16;quoi:1;dangers:1;combien:1;hightech:1...   62   F
1   2                     restaurant:1;marrakech.shtml:1   35   M
2   3  payer:1;faq:1;taxe:1;habitation:1;macron:1;qui...   45   F
3   4  rigaud:3;laurent:3;photo:11;profile:8;photopro...   46   F
4   5  societe:1;disparition:1;proche:1;m%c3%a9lanie....   42   F
5   6  portes:1;prives:1;entre:1;conso:1;mer:1;enfant...   49   F
6   8  son:1;laposte:1;forum:1;mobile:1;affich:1;forf...   47   F
7   9  location:1;preavis:1;mois:1;faq:1;modele:1;dep...   52   M
8  12  iphone:1;homme:1;vue:1;deuxieme:1;internet:1;g...   49   F
9  13                                                NaN   46   M

# Final function to split the keywords and the frequency by id

In [76]:
def tidy_split(df, column, sep=';', keep=False):
    indexes = list()
    new_values = list()
    new_freq = list()
    df = df.dropna(subset=[column])
    for i, presplit in enumerate(df[column].astype(str)):
        values = presplit.split(sep)
        if keep and len(values) > 1:
            indexes.append(i)
            new_values.append(presplit)
        for value in values:
            indexes.append(i)
            new_values.append(value.split(":")[0])
            new_freq.append(value.split(":")[1]) if len(value.split(":")) > 1 else  new_freq.append(0)
    new_df = df.iloc[indexes, :].copy()
    new_df[column] = new_values
    new_df['frequency'] = new_freq
    return new_df

In [80]:
# Split des 10 1ères lignes 
df2 = tidy_split(df[:1000000], 'keywords', sep = ';', keep=False)

In [59]:
df3 = tidy_split_true(df[:300000], 'keywords', sep = ';', keep=False)

In [81]:
df2

            ID      keywords  age sex frequency
0            1         fibre   62   F        16
0            1          quoi   62   F         1
0            1       dangers   62   F         1
0            1       combien   62   F         1
0            1      hightech   62   F        16
0            1           que   62   F        16
0            1           est   62   F         1
0            1       recevra   62   F         1
0            1     operateur   62   F         1
0            1       quelles   62   F         1
0            1  installation   62   F         1
0            1         monde   62   F         1
0            1          tout   62   F         1
0            1        oblige   62   F         1
0            1   differences   62   F         1
0            1        existe   62   F         1
0            1          adsl   62   F         1
0            1       choisir   62   F         1
0            1      concerne   62   F         1
0            1         sante   62   F         1
0            1  telephonique   62   F         1
0            1           com   62   F         1
0            1          chez   62   F         1
0            1         faire   62   F         1
0            1        quelle   62   F         1
0            1         debit   62   F         1
0            1           les   62   F         2
0            1         cable   62   F         1
0            1         quels   62   F         2
0            1          fttb   62   F         1
...        ...           ...  ...  ..       ...
999996  437055          noah   31   M         1
999996  437055    kickboxing   31   M         1
999996  437055       societe   31   M        15
999996  437055        banner   31   M         1
999996  437055   conducteurs   31   M         1
999996  437055      emmanuel   31   M         1
999996  437055        macron   31   M         1
999996  437055      champion   31   M         1
999996  437055         conge   31   M        15
999996  437055       marlene   31   M        15
999996  437055      societes   31   M         1
999996  437055         place   31   M         1
999996  437055          fuir   31   M         1
999996  437055       empeche   31   M         1
999996  437055         sport   31   M         1
999997   18211           faq   46   F         1
999997   18211       tremble   46   F         1
999997   18211           qui   46   F         1
999997   18211        causes   46   F         1
999997   18211      paupiere   46   F         1
999997   18211     solutions   46   F         1
999998   44638     mobiliser   34   F         1
999998   44638       travail   34   F         1
999998   44638        contre   34   F         1
999998   44638           cgt   34   F         1
999998   44638        social   34   F         1
999998   44638           loi   34   F         1
999998   44638         peine   34   F         1
999999   44641           mot   45   M         1
999999   44641     citations   45   M         1

[17699607 rows x 5 columns]

In [82]:
df2[df2['frequency'] == 0]

            ID                             keywords  age sex frequency
202135  288556     000229badebbb2dac8d54a4bb2ac2486   53   M         0
264055   29205      000006481947cd874af88d654770105   36   F         0
267323  381633  00004877-2fe6-412d-9307-a20dada1a11   51   M         0
356731   51157      0006d6dc4326ff03a2aa336205be392   48   M         0
373565  533268     00090d1f45c84e532ca92b4f5ecab0d2   65   F         0
429452  613254      000a26b6382e9a69a9921f729ddf4bc   31   F         0
432249  617250      000106e87411e153dede64537ceb0dc   37   F         0
459950  223419      0001db7a07e8c6c776fde7bbbf560f4   35   F         0
473817  676749      0001f89338ba08ba3b177dfd9707ea0   36   M         0
507476  302632      00009a1a7b2aea6e8138c041cba6042   43   F         0
552106   29205      000309b1db267cf6fd678a680abc519   36   F         0
574412  820070      0009b12374f520a86e695272b47979f   41   F         0
608596  868880  000214c5-489a-4d79-9a09-e990281b223   33   M         0
752569   92910     0004e969cc76d7f78b185b17cd1045cd   50   M         0
824855  265951      000026ee429cb4a5d08d78ff644ae8f   59   M         0
897019   29205      000006481947cd874af88d654770105   36   F         0

In [79]:
df2[df2['keywords'] == 'que']

     ID keywords  age sex frequency
0     1      que   62   F        16
31   46      que   74   F        13
55   77      que   40   F        20
55   77      que   40   F         1
62   88      que   57   F         2
67   96      que   46   F         1
79  113      que   72   M         3

In [59]:
df2[df2['keywords'] == 'fibre']

     ID keywords  age sex frequency
0     1    fibre   62   F        16
79  113    fibre   72   M         3

# Group by id and sum keywords frequency

In [113]:
df_count = df2.drop({'ID','age','sex'}, axis = 1)
df_count['frequency'] = df_count['frequency'].astype(int)

In [114]:
df_count

             keywords  frequency
0               fibre         16
0                quoi          1
0             dangers          1
0             combien          1
0            hightech         16
0                 que         16
0                 est          1
0             recevra          1
0           operateur          1
0             quelles          1
0        installation          1
0               monde          1
0                tout          1
0              oblige          1
0         differences          1
0              existe          1
0                adsl          1
0             choisir          1
0            concerne          1
0               sante          1
0        telephonique          1
0                 com          1
0                chez          1
0               faire          1
0              quelle          1
0               debit          1
0                 les          2
0               cable          1
0               quels          2
0                fttb          1
..                ...        ...
92               vous          1
92               band          1
92                les          1
92             maelys          6
92            travail          1
92             social          1
92         definition          1
92               foie          1
92             partir          1
92     tounsia.amrani          1
98             prenom          4
98            prenoms          4
98                top          4
98              fille          4
98         classement          4
99           resultat          2
99         immobilier          1
99           annonces          2
99            annonce          1
99  saint+cloud+92210          1
99        differentes          1
99           surfaces          1
99          recherche          1
99             affich          1
99                loi          1
99               deux          1
99              vente          2
99             carrez          1
99              forum          1
99        appartement          1

[2472 rows x 2 columns]

In [120]:
sum_of_count = df_count.groupby('keywords').frequency.sum()

In [121]:
sum_of_count

keywords
035f9d604401              1
11e7                      9
182618                    1
1er                       2
2799                      1
28a86c911c0f              1
2a89697ebd5f              1
312751                    1
3_78b6c5ae                1
74e                       1
786a                      1
7dc3                      1
8e50                      1
8e5f                      1
8f04                      1
8f16                      3
988f                      1
9fe8                      1
_097480e0                 1
abonnement                1
abonnements               3
abonner                   1
accept                    1
accords                   1
accoucher                 1
accueil_candidatures      9
acheteront                2
actu                     61
actualite                29
actualites                6
                       ...
victoria                  5
vidange                   1
video                     4
vie                       3
ville                    10
vin                       8
vincennes                 1
vincent                   2
vins                     11
violences                 1
vite                      1
voitures                  2
volkswagen               10
vont                      1
vous                     22
vox                       7
voyage                    2
vue                      70
wachowski                 1
wait                      2
wauquiez                  1
week                    230
whitney                   2
williams                  1
yeux                      3
zagreb                    1
zahia                     3
zele                      1
zizou                     2
zuckerberg                1
Name: frequency, Length: 1234, dtype: int32

In [123]:
df_count[df_count.keywords == 'fibre']

   keywords  frequency
0     fibre         16
79    fibre          3

In [124]:
df_count[df_count.keywords == 'fibre'].frequency.sum()

19